
## This file creates the data for the mark-resight multi-event model 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r set up}

library(here) #v1.0.1
library(dplyr) #v1.0.5
library(lubridate) #v1.7.20
library(reshape2) #v1.4.4
library(Hmisc) #v4.5-0; %nin%

```


```{r create CH}

#initial branding data (site, weight, sex, etc) for w.DPS
inits_raw_eDPS <- read.csv(here::here('data', "MML_ODFW_SSL_initCaps_070122.csv"), 
                  header = T, stringsAsFactors = F)

inits_eDPS <- inits_raw_eDPS %>%
  transform(Sex = ifelse(!is.na(AdjustedSex), AdjustedSex, Sex)) %>%
  dplyr::select(AnimalID, Year, Region, SiteName, Sex, Age, 
                Mass_kg) %>%
  dplyr::rename(t_0 = Year, site_0 = SiteName, reg_0 = Region) %>%
  filter(t_0 > 1999 & t_0 < 2020) %>% 
  dplyr::rename(branding_age = Age) %>%
  transform(Mass_kg = ifelse(is.na(Mass_kg), NA, Mass_kg)) 
  
inits_f <- inits_eDPS %>% filter(Sex == 'F') 
inits_m <- inits_eDPS %>% filter(Sex == 'M') 

#FEMALES
res_raw_eDPS <- read.csv(here::here('data', 'MML_ODFW_SSL_resightData_070122.csv'), 
                     header = T, stringsAsFactors = F) 

resights <- res_raw_eDPS %>%
  #sex from branding is more complete, but contains a few mistakes, so use sex from resights 
  dplyr::select(-c(Sex, Beach, Platform, Time, Age, pup_evidence, Behavior)) %>% 
  merge(inits_eDPS, by = c('AnimalID'), all.y = T) %>% 
  transform(year = year(datetime)) %>% 
  transform(year = coalesce(year, t_0)) %>% #grab branding year if never resighted (and therefore no date in res_raw)
  transform(years_old = year - t_0) %>%
  filter(year < 2020) %>%
  transform(SiteName = trimws(SiteName, which = c("both", "left", "right"))) %>%
  transform(age_cat = ifelse(years_old > 9, 'A', years_old)) %>%
  transform(age_cat_num = as.numeric(factor(age_cat))) %>%
  #standardize by sex?
  transform(Mass_kg = ifelse(is.na(Mass_kg), 0, Mass_kg)) %>%
  transform(Mass_std = scale(Mass_kg)) 

#annual level CH observations
#resights for branded pups were only entered mainly for Oregon-branded individuals -- be mindful for inits
ch_dat <- resights %>% 
  arrange(t_0) %>% 
  distinct(AnimalID, year, Sex, site_0, t_0, age_cat_num, Mass_std) %>%
  reshape2::dcast(AnimalID + t_0 + site_0 + Mass_std + Sex ~ year, value.var = 'age_cat_num', fill = 12) %>%
  arrange(AnimalID)


```

```{r write csvs}

## ALL INDIVIDUALS

write.csv(ch_dat, file = here::here('data', 'ch_dat.csv'), row.names = F)

```

```{r brands per year}

#table of n_ids by year and region
brands <- inits %>%
  dplyr::select(AnimalID, t_0, reg_0) %>% distinct() %>%
  reshape2::dcast(reg_0 ~ t_0, value.var = 'AnimalID') %>%
  transform(reg_0 = factor(reg_0, levels = c('E GULF', 'C GULF', 'E ALEU', 'C ALEU', 'W ALEU'))) %>%
  arrange(reg_0)

```

```{r weights by region}

weights_f <- resights %>%
  distinct(AnimalID, Mass_kg, reg_0, Sex)

weights_m <- resights_m %>%
  distinct(AnimalID, Mass_kg, reg_0, Sex)

weights <- rbind(weights_f, weights_m) %>%
  transform(reg = ifelse(reg_0 %in% c('C ALEU', 'W ALEU'), 'western', 'eastern'))

ggplot(weights, aes(reg, Mass_kg, col = Sex, group = Sex)) +
  geom_violin(draw_quantiles = c(0.025, 0.5, 0.975)) +
  facet_grid(~reg)

weights_sum <- weights %>%
  group_by(Sex, reg) %>%
  dplyr::summarize(mean = mean(Mass_kg), sd = sd(Mass_kg))

```

