

```{r setup, include = F}

knitr::opts_chunk$set(echo = FALSE, eval = FALSE, message = F, warning = F)

library(here) #v1.0.1
library(dplyr) #v1.0.5
library(nimble) #v0.12.1

source(here::here('scripts', 'PlotTheme.R'))


```

```{r params states}
# Parameters:
# phiP surv pup to yearling
# phi1 surv of yearling
# phi2 surv of 2 year old
# phi3 surv of 3 pre-breeder
# phi4 surv of 4 pre-breeder
# phi5 surv of 5 pre-breeder
# phiB surv of breeders 6+ years old
# phiN surv of NB breeders 5+ years old 
# phiPM surv pup to yearling male
# phi1M surv of yearling male
# phi2M surv of 2 male
# phi3M surv of 3 male
# phi4M surv of 4 male
# phi5M surv of 5 male
# phiBM surv of adult male
    
# psi3B = prob of 3 year old becoming 4 year old B
# psi4B = prob of 4 year old becoming 5 year old B
# psi5B = prob of 5 year old becoming 6 year old B 
# psiBB = prob of staying breeder given were a breeder
# psiNB = prob of becoming breeder given were a NB

# p1 = detection of yearling
# P2 = detection of 2
# p3 = detection of 3 
# p4 = detection of 4
# p5 = detection of 5
# pB = detection of B
# pNB = detection of NB 
# p1M = detection of yearling male
# P2M = detection of 2 male
# p3M = detection of 3 male
# p4M = detection of 4 male
# p5M = detection of 5 male
# pBM = detection of territorial males 6+
# delB = prob of correctly ascertaining presence of pup for breeders

# OBSERVATIONS
# 1 = pup w/o
# 2 = 1 w/o
# 3 = 2 w/o
# 4 = 3 w/o
# 5 = 4 w/o
# 6 = 4 w
# 7 = 5 w/o
# 8 = 5 w
# 9 = 6+ w/o
# 10 = 6+ w
# 11 = ND
# 1 = pup male
# 2 = 1yo male
# 3 = 2yo male
# 4 = 3 male
# 5 = 4 male
# 6 = 5 male
# 7 = 6+ male 
# 9 = ND male

# STATES
# females
# 1 = pup
# 2 = yearling
# 3 = age-2
# 4 = pre-breeding age-3
# 5 = pre-breeding age-4
# 6 = pre-breeding age-5
# 7 = age-4 w/ pup
# 8 = age-5 w/ pup
# 9 = age-6+ w/ pup
# 10 = age-5 non-breeder
# 11 = age-6+ non-breeder
# 12 = dead
# males
# 1 = pup
# 2 = yearling
# 3 = age-2
# 4 = age-3
# 5 = age-4
# 6 = age-5
# 7 = adult male
# 8 = dead

#4 yo natality: states 7/(5+7)
#5 yo natality: states 8/(8+6+10)
#6+ yo natality: states 9/(9+11)


```

```{r nimble functions}

#state transition - females
getPHI <- nimbleFunction(
  run = function(z=double(0), phiP=double(0), phi1=double(0), phi2=double(0), phi3=double(0), phi4=double(0),
                 phi5=double(0), phi6=double(0), phi7=double(0), phi8=double(0), 
                 phi9=double(0), phiA=double(0)) {
   returnType(double(1))
   ans <- rep(0,12)
     if(z==1)   ans <- c(0,phiP,0,0,0,0,0,0,0,0,0,1-phiP)  #pup
     if(z==2)   ans <- c(0,0,phi1,0,0,0,0,0,0,0,0,1-phi1)  #yearling   
     if(z==3)   ans <- c(0,0,0,phi2,0,0,0,0,0,0,0,1-phi2)  #2yr
     if(z==4)   ans <- c(0,0,0,0,phi3,0,0,0,0,0,0,1-phi3)  #3yr 
     if(z==5)   ans <- c(0,0,0,0,0,phi4,0,0,0,0,0,1-phi4)  #4yr
     if(z==6)   ans <- c(0,0,0,0,0,0,phi5,0,0,0,0,1-phi5)  #5yr           
     if(z==7)   ans <- c(0,0,0,0,0,0,0,phi6,0,0,0,1-phi6)  #6yr 
     if(z==8)   ans <- c(0,0,0,0,0,0,0,0,phi7,0,0,1-phi7)       
     if(z==9)   ans <- c(0,0,0,0,0,0,0,0,0,phi8,0,1-phi8)       
     if(z==10)  ans <- c(0,0,0,0,0,0,0,0,0,0,phi9,1-phi9)   
     if(z==11)  ans <- c(0,0,0,0,0,0,0,0,0,0,phiA,1-phiA)       
     if(z==12)  ans <- c(0,0,0,0,0,0,0,0,0,0,0,1) #D

   return(ans)
 }
)

#observations 
getP <- nimbleFunction(
  run = function(z=double(0), p1=double(0), p2=double(0), p3=double(0), p4=double(0), p5=double(0),
                 p6=double(0), p7=double(0), p8=double(0), p9=double(0), pA=double(0)) {
   returnType(double(1))
   ans <- rep(0,12)
     if(z==1)   ans <- c(1,0,0,0,0,0,0,0,0,0,0,0) #pups seen as pups
     if(z==2)   ans <- c(0,p1,0,0,0,0,0,0,0,0,0,1-p1)   #1yr      
     if(z==3)   ans <- c(0,0,p2,0,0,0,0,0,0,0,0,1-p2)   #2yr
     if(z==4)   ans <- c(0,0,0,p3,0,0,0,0,0,0,0,1-p3)   #3yr
     if(z==5)   ans <- c(0,0,0,0,p4,0,0,0,0,0,0,1-p4)   #4yr 
     if(z==6)   ans <- c(0,0,0,0,0,p5,0,0,0,0,0,1-p5)   #5yr           
     if(z==7)   ans <- c(0,0,0,0,0,0,p6,0,0,0,0,1-p6)   #6yr  
     if(z==8)   ans <- c(0,0,0,0,0,0,0,p7,0,0,0,1-p7)   #7yr  
     if(z==9)   ans <- c(0,0,0,0,0,0,0,0,p8,0,0,1-p8)   #8yr  
     if(z==10)  ans <- c(0,0,0,0,0,0,0,0,0,p9,0,1-p9)   #9yr  
     if(z==11)  ans <- c(0,0,0,0,0,0,0,0,0,0,pA,1-pA)   #pA
     if(z==12)  ans <- c(0,0,0,0,0,0,0,0,0,0,0,1)       #nd

   return(ans)
 }
)

```

```{r load data, echo = F, eval = T}

## capture histories
ch_dat <- read.csv(here::here('data', 'ch_dat.csv'),
                   header = T, stringsAsFactors = F) %>%
  filter(!is.na(Sex)) %>% #two individuals with unknown sex
  filter(t_0 < 2018) %>% #just 4 individuals branded 2018-2019
  filter(site_0 != 'BONNEVILLE DAM')

## variables and dimensions
n_occasions <- dim(ch_dat)[2]-5 #subtract id columns

#need to re-standardize this for males/females
mass <- ch_dat$Mass_std
sex <- as.numeric(factor(ch_dat$Sex)) #female == 1, male == 2
rook <- as.numeric(factor(ch_dat$site_0)) 

#levels = c("BONNEVILLE DAM", PYRAMID ROCK", "SOUTH SEAL ROCK")
 # BONNEVILLE DAM    PYRAMID ROCK SOUTH SEAL ROCK 
 #             50            1395             290 

#so few individuals branded at bonneville damn - combine for two-level covariate?
# rook[which(rook == 3)] <- 1

```

```{r fc inits}

#first capture
#because not all pups are "resighted" in their branding year - a bit of gymnastics
yrs <- c(2001:2019)
fc <- as.numeric(factor(ch_dat$t_0, levels = yrs))

#make 1's for all fc, NA beforehand
ch <- ch_dat[,-c(1:5)]
for (i in 1:dim(ch)[1]) {
  ch[i,fc[i]] <- 1
  if(fc[i] > 1) {ch[i, 1:(fc[i]-1)] <- NA }
}

y <- as.matrix(ch)

# Initial values for possible states
# "NA" for the latent state at all places before an individual was observed

cjs.init <- function(ch, fc){
  inits <- ch    #initialize with observations up until states diverge from observations (4yr olds)
  for(i in 1:dim(ch)[1]) {
    # for(i in 1:10) { 
    inits[i,fc[i]] <- NA #pups at release
      if(n_occasions-fc[i]>=1){   
        inits[i,(fc[i] + 1)] <- 2} #1 yr old
      if(n_occasions-fc[i]>=2){
        inits[i,(fc[i] + 2)] <- 3}  #2 yr old
      if(n_occasions-fc[i]>=3){
        inits[i,(fc[i] + 3)] <- 4} #3 yr old
    if(n_occasions-fc[i]>=4){
        inits[i,(fc[i] + 4)] <- 5}
    if(n_occasions-fc[i]>=5){
        inits[i,(fc[i] + 5)] <- 6}
    if(n_occasions-fc[i]>=6){
        inits[i,(fc[i] + 6)] <- 7}
    if(n_occasions-fc[i]>=7){
        inits[i,(fc[i] + 7)] <- 8}
    if(n_occasions-fc[i]>=8){
        inits[i,(fc[i] + 8)] <- 9}
    if(n_occasions-fc[i]>=9){
        inits[i,(fc[i] + 9)] <- 10}
      if(n_occasions-fc[i]>=10) {
        inits[i,((fc[i] + 10):n_occasions)] <- 11} #all 10yrs+ are A
  } #i
  return(inits)
}

z.init = as.matrix(cjs.init(ch, fc))

## recapture summary stats
#i=1 lots of resights
#i=6 single resight
#i=2 no resights
# capt <- numeric()
# for (i in 1:dim(ch)[1]) {
#   capt[i] <- as.numeric(sum(ch[i,(fc[i]+1):n_occasions]<11)<1) #will be TRUE for inds never recapt
# }
# 
# #capt==1 for inds never resighted; 553/1322 == 41%
# sum(capt>0)/length(capt)
# 
# capt_m <- numeric()
# for (i in 1:dim(ch_m)[1]) {
#   capt_m[i] <- as.numeric(sum(ch_m[i,(fc_m[i]+1):n_occasions]<8)<1) #will be TRUE for inds never recapt
# }
# 
# #capt==1 for inds never resighted; 622/1330 == 47%
# sum(capt_m>0)/length(capt_m)
# 
# ## distribution of resights for females
# res_actual <- read.csv(here::here('SSL_CJS', 'Data', 'resights_actual.csv'), 
#                        header = T, stringsAsFactors = F)
# res_actual <- res_actual[,2:(n_occasions+1)]
# 
# capt_freq <- capt_sd <- numeric()
# for (i in 1:dim(res_actual)[1]) { 
# 
#   cols <- which(res_actual[i,]!=0)
#   capt_freq[i] <- mean(as.numeric(res_actual[i,cols[which(cols>fc[i])]])) #average per ind across yrs
#   capt_sd[i] <- sd(as.numeric(res_actual[i,cols[which(cols>fc[i])]])) #variability across yrs
# }

#individuals recaptured an average of 6 times per year
# capt_freq_avg <- mean(capt_freq, na.rm = T)
# #variability in recaptures across individuals: 7.1
# capt_sd_avg <- sd(capt_freq, na.rm = T) 

```

```{r null model text}

SSL_CJS <- nimbleCode({

# Priors and constraints
  for (i in 1:n_ind) { #females
    for (t in 1:(n_occasions - 1)) {
      logit(phiP[i,t]) <- mu.P 
      logit(p1[i,t]) <- mean.p1 
    } #t 
    
    for (t in 2:(n_occasions-1)) {
      logit(phi1[i,t]) <- mu.1  
      logit(p2[i,t]) <- mean.p2 
    }
    
    for (t in 3:(n_occasions-1)) {
      logit(phi2[i,t]) <- mu.2 
      logit(p3[i,t]) <- mean.p3 
    }
    
    #first cohort branded in 2001, turn 1 in 2002,
    for (t in 4:(n_occasions-1)) { 
      logit(phi3[i,t]) <- mu.3 
      logit(p4[i,t]) <- mean.p4  
    } #t psi
    
    for (t in 5:(n_occasions-1)) {
      logit(phi4[i,t]) <- mu.4 
      logit(p5[i,t]) <- mean.p5 
    } #t 
    
    for (t in 6:(n_occasions-1)) {  
      logit(phi5[i,t]) <- mu.5 
      logit(p6[i,t]) <- mean.p6
    } #t 
    
    for (t in 7:(n_occasions-1)) {  
      logit(phi6[i,t]) <- mu.6 
      logit(p7[i,t]) <- mean.p7
    } #t 
    
    for (t in 8:(n_occasions-1)) {  
      logit(phi7[i,t]) <- mu.7 
      logit(p8[i,t]) <- mean.p8
    } #t 
    
    for (t in 9:(n_occasions-1)) {  
      logit(phi8[i,t]) <- mu.8
      logit(p9[i,t]) <- mean.p9
    } #t 
    
    for (t in 10:(n_occasions-1)) {  
      logit(phi9[i,t]) <- mu.9
      logit(pA[i,t]) <- mean.pA
    } #t 
    
    for (t in 11:(n_occasions-1)) {  
      logit(phiA[i,t]) <- mu.A 
    } #t 
    
  } #ind
  
  
### Priors
    #p
    mean.p1 <- log(int.p1/(1 - int.p1))
    mean.p2 <- log(int.p2/(1 - int.p2))
    mean.p3 <- log(int.p3/(1 - int.p3))
    mean.p4 <- log(int.p4/(1 - int.p4))
    mean.p5 <- log(int.p5/(1 - int.p5))
    mean.p6 <- log(int.p6/(1 - int.p6))
    mean.p7 <- log(int.p7/(1 - int.p7))
    mean.p8 <- log(int.p8/(1 - int.p8))
    mean.p9 <- log(int.p9/(1 - int.p9))
    mean.pA <- log(int.pA/(1 - int.pA))

    int.p1 ~ dunif(0,1)
    int.p2 ~ dunif(0,1)
    int.p3 ~ dunif(0,1)
    int.p4 ~ dunif(0,1)
    int.p5 ~ dunif(0,1)
    int.p6 ~ dunif(0,1)
    int.p7 ~ dunif(0,1)
    int.p8 ~ dunif(0,1)
    int.p9 ~ dunif(0,1)
    int.pA ~ dunif(0,1)

    #phi
    mu.P <- log(int.phiP/(1 - int.phiP))
    mu.1 <- log(int.phi1/(1 - int.phi1))
    mu.2 <- log(int.phi2/(1 - int.phi2))
    mu.3 <- log(int.phi3/(1 - int.phi3))
    mu.4 <- log(int.phi4/(1 - int.phi4))
    mu.5 <- log(int.phi5/(1 - int.phi5))
    mu.6 <- log(int.phi6/(1 - int.phi6))
    mu.7 <- log(int.phi7/(1 - int.phi7))
    mu.8 <- log(int.phi8/(1 - int.phi8))
    mu.9 <- log(int.phi9/(1 - int.phi9))
    mu.A <- log(int.phiA/(1 - int.phiA))
    
    int.phiP ~ dunif(0,1)
    int.phi1 ~ dunif(0,1)
    int.phi2 ~ dunif(0,1)
    int.phi3 ~ dunif(0,1)
    int.phi4 ~ dunif(0,1)
    int.phi5 ~ dunif(0,1)
    int.phi6 ~ dunif(0,1)
    int.phi7 ~ dunif(0,1)
    int.phi8 ~ dunif(0,1)
    int.phi9 ~ dunif(0,1)
    int.phiA ~ dunif(0,1)
    
    #likelihood
for (i in 1:n_ind) { #females
    z[i, fc[i]:fc[i]] <- 1 #pups at first capture

for (t in (fc[i] + 1):n_occasions) {
      z[i,t] ~ dcat(state_probs[i,t-1,1:12])
      y[i,t] ~ dcat(event_probs[i,t,1:12])
      
    state_probs[i,t-1,1:12] <- getPHI(z = z[i,t-1], 
                                      phiP = phiP[i,t-1], phi1 = phi1[i,t-1], phi2 = phi2[i,t-1], 
                                      phi3 = phi3[i,t-1], phi4 = phi4[i,t-1], phi5 = phi5[i,t-1], 
                                      phi6 = phi6[i,t-1], phi7 = phi7[i,t-1], phi8 = phi8[i,t-1],
                                      phi9 = phi9[i,t-1], phiA = phiA[i,t-1])
    
    event_probs[i,t,1:12] <- getP(z = z[i,t], 
                                    p1 = p1[i,t-1], p2 = p2[i,t-1], p3 = p3[i,t-1], 
                                    p4 = p4[i,t-1], p5 = p5[i,t-1], p6 = p6[i,t-1],
                                    p7 = p7[i,t-1], p8 = p8[i,t-1], p9 = p9[i,t-1],
                                    pA = pA[i,t-1])
    } #t likelihood 
} #i likelihood 
    
}) # mod   

##### run model ####
nim.data <- list(y = y)

nim.constants <- list(n_ind = dim(ch)[1], n_occasions = n_occasions,
                      mass = mass, rook = rook, sex = sex,
                      fc = fc)

inits <- list(int.phiP = 0.9, int.phi1 = 0.9, int.phi2 = 0.9, int.phi3 = 0.9,
              int.phi4 = 0.9, int.phi5 = 0.9, 
              mean.p1 = qlogis(0.7), mean.p2 = qlogis(0.6),
              mean.p3 = qlogis(0.6),mean.p4 = qlogis(0.6),
              mean.p5 = qlogis(0.4),
              z = z.init)

### parameters
params <- c('int.p1', 'int.p2', 'int.p3', 'int.p4', 'int.p5', 'int.p6', 'int.p7', 'int.p8', 
            'int.p9', 'int.pA', 
            'int.phiP', 'int.phi1', 'int.phi2', 'int.phi3', 'int.phi4', 'int.phi5', 
            'int.phi6', 'int.phi7', 'int.phi8', 'int.phi9', 'int.phiA',
            # 'b.massP', 'b.mass', 'b.sexP', 'b.sex1', 'b.sex2', 'b.sex3', 'b.sex4', 'b.sex5', 'b.sex6', 
            # 'b.sexA', 'b.siteP', 'b.site1', 'b.site2', 'b.siteJ', 'b.siteA',
            'z')

### run model
n.iter = 3500; n.chains = 3; n.burnin = 2000; nthin = 3; nAdapt = 20
# n.iter = 35000; n.chains = 3; n.burnin = 20000; nthin = 3; nAdapt = 20


start <- Sys.time()

Rmodel <- nimbleModel(code = SSL_CJS, 
                      constants = nim.constants, data = nim.data, 
                      calculate = F, check = F, inits = inits)

conf <- configureMCMC(Rmodel, monitors = params, control = list(adaptInterval = nAdapt), 
                      thin = nthin, useConjugacy = FALSE, enableWAIC = TRUE)

Rmcmc <- buildMCMC(conf)  #produce uncompiled R mcmc function
Cmodel <- compileNimble(Rmodel)
Cmcmc <- compileNimble(Rmcmc, project = Rmodel)

out <- runMCMC(Cmcmc, niter = n.iter, nburnin = n.burnin, nchains = n.chains, inits = inits,
                 setSeed = FALSE, progressBar = TRUE,
               WAIC = TRUE, samplesAsCodaMCMC = TRUE)

saveRDS(out, here::here('results', 'out_null.RDS')) 

```

```{r fixed effects sex site weight model text}

SSL_CJS <- nimbleCode({

# Priors and constraints
  for (i in 1:n_ind) { 
    for (t in 1:(n_occasions - 1)) {
      logit(phiP[i,t]) <- mu.P + b.sexP[sex[i]] + b.massP*mass[i] + b.siteP[site[i]]
      logit(p1[i,t]) <- mean.p1 
    } #t 
    
    for (t in 2:(n_occasions-1)) {
      logit(phi1[i,t]) <- mu.1 + b.sex1[sex[i]] + b.mass*mass[i] + b.site1[site[i]]
      logit(p2[i,t]) <- mean.p2 
    }
    
    for (t in 3:(n_occasions-1)) {
      logit(phi2[i,t]) <- mu.2 + b.sex2[sex[i]] + b.site2[site[i]]
      logit(p3[i,t]) <- mean.p3 
    }
    
    for (t in 4:(n_occasions-1)) { 
      logit(phi3[i,t]) <- mu.3 + b.sex3[sex[i]] + b.siteJ[site[i]]
      logit(p4[i,t]) <- mean.p4  
    } #t psi
    
    for (t in 5:(n_occasions-1)) {
      logit(phi4[i,t]) <- mu.4 + b.sex4[sex[i]] + b.siteJ[site[i]]
      logit(p5[i,t]) <- mean.p5 
    } #t 
    
    for (t in 6:(n_occasions-1)) {  
      logit(phi5[i,t]) <- mu.5 + b.sex5[sex[i]] + b.siteJ[site[i]]
      logit(p6[i,t]) <- mean.p6
    } #t 
    
    for (t in 7:(n_occasions-1)) {  
      logit(phi6[i,t]) <- mu.6 + b.sex6[sex[i]] + b.siteJ[site[i]]
      logit(p7[i,t]) <- mean.p7
    } #t 
    
    for (t in 8:(n_occasions-1)) {  
      logit(phi7[i,t]) <- mu.7 + b.sexA[sex[i]] + b.siteA[site[i]]
      logit(p8[i,t]) <- mean.p8
    } #t 
    
    for (t in 9:(n_occasions-1)) {  
      logit(phi8[i,t]) <- mu.8 + b.sexA[sex[i]] + b.siteA[site[i]]
      logit(p9[i,t]) <- mean.p9
    } #t 
    
    for (t in 10:(n_occasions-1)) {  
      logit(phi9[i,t]) <- mu.9 + b.sexA[sex[i]] + b.siteA[site[i]]
      logit(pA[i,t]) <- mean.pA
    } #t 
    
    for (t in 11:(n_occasions-1)) {  
      logit(phiA[i,t]) <- mu.A + b.sexA[sex[i]] + b.siteA[site[i]]
    } #t 
    
  } #ind
  
### Priors
    #p
    mean.p1 <- log(int.p1/(1 - int.p1))
    mean.p2 <- log(int.p2/(1 - int.p2))
    mean.p3 <- log(int.p3/(1 - int.p3))
    mean.p4 <- log(int.p4/(1 - int.p4))
    mean.p5 <- log(int.p5/(1 - int.p5))
    mean.p6 <- log(int.p6/(1 - int.p6))
    mean.p7 <- log(int.p7/(1 - int.p7))
    mean.p8 <- log(int.p8/(1 - int.p8))
    mean.p9 <- log(int.p9/(1 - int.p9))
    mean.pA <- log(int.pA/(1 - int.pA))

    int.p1 ~ dunif(0,1)
    int.p2 ~ dunif(0,1)
    int.p3 ~ dunif(0,1)
    int.p4 ~ dunif(0,1)
    int.p5 ~ dunif(0,1)
    int.p6 ~ dunif(0,1)
    int.p7 ~ dunif(0,1)
    int.p8 ~ dunif(0,1)
    int.p9 ~ dunif(0,1)
    int.pA ~ dunif(0,1)

    #phi
    mu.P <- log(int.phiP/(1 - int.phiP))
    mu.1 <- log(int.phi1/(1 - int.phi1))
    mu.2 <- log(int.phi2/(1 - int.phi2))
    mu.3 <- log(int.phi3/(1 - int.phi3))
    mu.4 <- log(int.phi4/(1 - int.phi4))
    mu.5 <- log(int.phi5/(1 - int.phi5))
    mu.6 <- log(int.phi6/(1 - int.phi6))
    mu.7 <- log(int.phi7/(1 - int.phi7))
    mu.8 <- log(int.phi8/(1 - int.phi8))
    mu.9 <- log(int.phi9/(1 - int.phi9))
    mu.A <- log(int.phiA/(1 - int.phiA))
    
    int.phiP ~ dunif(0,1)
    int.phi1 ~ dunif(0,1)
    int.phi2 ~ dunif(0,1)
    int.phi3 ~ dunif(0,1)
    int.phi4 ~ dunif(0,1)
    int.phi5 ~ dunif(0,1)
    int.phi6 ~ dunif(0,1)
    int.phi7 ~ dunif(0,1)
    int.phi8 ~ dunif(0,1)
    int.phi9 ~ dunif(0,1)
    int.phiA ~ dunif(0,1)
    
    b.sexP[1] <- 0
    b.sex1[1] <- 0
    b.sex2[1] <- 0
    b.sex3[1] <- 0
    b.sex4[1] <- 0
    b.sex5[1] <- 0
    b.sex6[1] <- 0
    b.sexA[1] <- 0
    b.sexP[2] ~ dnorm(0, sd = s.sexP)
    b.sex1[2] ~ dnorm(0, sd = s.sex1)
    b.sex2[2] ~ dnorm(0, sd = s.sex2)
    b.sex3[2] ~ dnorm(0, sd = s.sex3)
    b.sex4[2] ~ dnorm(0, sd = s.sex4)
    b.sex5[2] ~ dnorm(0, sd = s.sex5)
    b.sex6[2] ~ dnorm(0, sd = s.sex6)
    b.sexA[2] ~ dnorm(0, sd = s.sexA)
    s.sexP ~ dexp(1)
    s.sex1 ~ dexp(1)
    s.sex2 ~ dexp(1)
    s.sex3 ~ dexp(1)
    s.sex4 ~ dexp(1)
    s.sex5 ~ dexp(1)
    s.sex6 ~ dexp(1)
    s.sexA ~ dexp(1)
    
    b.massP ~ dnorm(0, sd = s.mass)
    b.mass ~ dnorm(0, sd = s.mass)
    s.mass ~ dexp(1)
    
    b.siteP[2] <- 0
    b.site1[2] <- 0
    b.site2[2] <- 0
    b.siteJ[2] <- 0
    b.siteA[2] <- 0
    b.siteP[1] ~ dnorm(0, sd = s.siteP)
    b.site1[1] ~ dnorm(0, sd = s.site1)
    b.site2[1] ~ dnorm(0, sd = s.site2)
    b.siteJ[1] ~ dnorm(0, sd = s.siteJ)
    b.siteA[1] ~ dnorm(0, sd = s.siteA)
    s.siteP ~ dexp(1)
    s.site1 ~ dexp(1)
    s.site2 ~ dexp(1)
    s.siteJ ~ dexp(1)
    s.siteA ~ dexp(1)
  
    #likelihood
for (i in 1:n_ind) { #females
    z[i, fc[i]:fc[i]] <- 1 #pups at first capture

for (t in (fc[i] + 1):n_occasions) {
      z[i,t] ~ dcat(state_probs[i,t-1,1:12])
      y[i,t] ~ dcat(event_probs[i,t,1:12])
      
    state_probs[i,t-1,1:12] <- getPHI(z = z[i,t-1], 
                                      phiP = phiP[i,t-1], phi1 = phi1[i,t-1], phi2 = phi2[i,t-1], 
                                      phi3 = phi3[i,t-1], phi4 = phi4[i,t-1], phi5 = phi5[i,t-1], 
                                      phi6 = phi6[i,t-1], phi7 = phi7[i,t-1], phi8 = phi8[i,t-1],
                                      phi9 = phi9[i,t-1], phiA = phiA[i,t-1])
    
    event_probs[i,t,1:12] <- getP(z = z[i,t], 
                                    p1 = p1[i,t-1], p2 = p2[i,t-1], p3 = p3[i,t-1], 
                                    p4 = p4[i,t-1], p5 = p5[i,t-1], p6 = p6[i,t-1],
                                    p7 = p7[i,t-1], p8 = p8[i,t-1], p9 = p9[i,t-1],
                                    pA = pA[i,t-1])
    } #t likelihood 
} #i likelihood 
    
}) # mod   

##### run model ####
nim.data <- list(y = y)

nim.constants <- list(n_ind = dim(ch)[1], n_occasions = n_occasions,
                      mass = mass, site = rook, sex = sex,
                      fc = fc)

inits <- list(int.phiP = 0.9, int.phi1 = 0.9, int.phi2 = 0.9, int.phi3 = 0.9, int.phiA = 0.9, 
              int.phi4 = 0.9, int.phi5 = 0.9, int.phi6 = 0.9, int.phi7 = 0.9, int.phi8 = 0.9, int.phi9 = 0.9, 
              mean.p1 = qlogis(0.7), mean.p2 = qlogis(0.6), mean.p3 = qlogis(0.6),
              mean.p4 = qlogis(0.6), mean.p5 = qlogis(0.4), mean.p6 = qlogis(0.6), mean.p7 = qlogis(0.6),
              mean.p8 = qlogis(0.4), mean.p9 = qlogis(0.6), mean.pA = qlogis(0.6),
              b.massP = 0, b.mass = 0, b.sexP = 0, b.sex1 = 0, b.sex2 = 0, b.sex3 = 0, b.sex4 = 0, 
              b.sex5 = 0, b.sex6 = 0, b.sexA = 0, b.siteP = 0, b.site1 = 0, b.site2 = 0, b.siteJ = 0, b.siteA = 0,
              z = z.init)

### parameters
params <- c('int.p1', 'int.p2', 'int.p3', 'int.p4', 'int.p5', 'int.p6', 'int.p7', 'int.p8', 
            'int.p9', 'int.pA', 
            'int.phiP', 'int.phi1', 'int.phi2', 'int.phi3', 'int.phi4', 'int.phi5', 
            'int.phi6', 'int.phi7', 'int.phi8', 'int.phi9', 'int.phiA',
            'b.massP', 'b.mass', 'b.sexP', 'b.sex1', 'b.sex2', 'b.sex3', 'b.sex4', 'b.sex5', 'b.sex6',
            'b.sexA', 'b.siteP', 'b.site1', 'b.site2', 'b.siteJ', 'b.siteA',
            'z')

### run model
n.iter = 3500; n.chains = 3; n.burnin = 2000; nthin = 3; nAdapt = 20
# n.iter = 35000; n.chains = 3; n.burnin = 20000; nthin = 3; nAdapt = 20


start <- Sys.time()

Rmodel <- nimbleModel(code = SSL_CJS, 
                      constants = nim.constants, data = nim.data, 
                      calculate = F, check = F, inits = inits)

conf <- configureMCMC(Rmodel, monitors = params, control = list(adaptInterval = nAdapt), 
                      thin = nthin, useConjugacy = FALSE, enableWAIC = TRUE)

Rmcmc <- buildMCMC(conf)  #produce uncompiled R mcmc function
Cmodel <- compileNimble(Rmodel)
Cmcmc <- compileNimble(Rmcmc, project = Rmodel)

out <- runMCMC(Cmcmc, niter = n.iter, nburnin = n.burnin, nchains = n.chains, inits = inits,
                 setSeed = FALSE, progressBar = TRUE,
               WAIC = TRUE,
               samplesAsCodaMCMC = TRUE)

saveRDS(out, here::here('results', 'out_FE.RDS')) 



```

```{r mixed effects time sex weight model text}

SSL_CJS <- nimbleCode({

# Priors and constraints
  for (i in 1:n_ind) { 
    for (t in 1:(n_occasions - 1)) {
      logit(phiP[i,t]) <- mu.P + b.sexP[sex[i]] + b.massP*mass[i] + epsP[t] + b.siteP[site[i]]
      logit(p1[i,t]) <- mean.p1 
      epsP[t] ~ dnorm(0, sd = sigmaP)

    } #t 
    
    for (t in 2:(n_occasions-1)) {
      logit(phi1[i,t]) <- mu.1 + b.sex1[sex[i]] + b.mass*mass[i] + eps1[t] +b.site1[site[i]]
      logit(p2[i,t]) <- mean.p2 
      eps1[t] ~ dnorm(0, sd = sigma1)
    }
    
    for (t in 3:(n_occasions-1)) {
      logit(phi2[i,t]) <- mu.2 + b.sex2[sex[i]] + eps2[t] + b.site2[site[i]]
      logit(p3[i,t]) <- mean.p3 
      eps2[t] ~ dnorm(0, sd = sigma2)
    }
    
    for (t in 4:(n_occasions-1)) { 
      logit(phi3[i,t]) <- mu.3 + b.sex3[sex[i]] + epsJ[t] + b.siteJ[site[i]]
      logit(p4[i,t]) <- mean.p4 
      epsJ[t] ~ dnorm(0, sd = sigmaJ)
    } #t psi
    
    for (t in 5:(n_occasions-1)) {
      logit(phi4[i,t]) <- mu.4 + b.sex4[sex[i]] + epsJ[t] + b.siteJ[site[i]]
      logit(p5[i,t]) <- mean.p5 
    } #t 
    
    for (t in 6:(n_occasions-1)) {  
      logit(phi5[i,t]) <- mu.5 + b.sex5[sex[i]] + epsJ[t] + b.siteJ[site[i]]
      logit(p6[i,t]) <- mean.p6
    } #t 
    
    for (t in 7:(n_occasions-1)) {  
      logit(phi6[i,t]) <- mu.6 + b.sex6[sex[i]] + epsJ[t] + b.siteJ[site[i]]
      logit(p7[i,t]) <- mean.p7
    } #t 
    
    for (t in 8:(n_occasions-1)) {  
      logit(phi7[i,t]) <- mu.7 + b.sexA[sex[i]] + epsA[t] + b.siteA[site[i]]
      logit(p8[i,t]) <- mean.p8
    } #t 
    
    for (t in 9:(n_occasions-1)) {  
      logit(phi8[i,t]) <- mu.8 + b.sexA[sex[i]] + epsA[t] + b.siteA[site[i]]
      logit(p9[i,t]) <- mean.p9
    } #t 
    
    for (t in 10:(n_occasions-1)) {  
      logit(phi9[i,t]) <- mu.9 + b.sexA[sex[i]] + epsA[t] + b.siteA[site[i]]
      logit(pA[i,t]) <- mean.pA
    } #t 
    
    for (t in 11:(n_occasions-1)) {  
      logit(phiA[i,t]) <- mu.A + b.sexA[sex[i]] + epsA[t] + b.siteA[site[i]]
      epsA[t] ~ dnorm(0, sd = sigmaA)
    } #t 
    
  } #ind
  
### Priors
    #p
    mean.p1 <- log(int.p1/(1 - int.p1))
    mean.p2 <- log(int.p2/(1 - int.p2))
    mean.p3 <- log(int.p3/(1 - int.p3))
    mean.p4 <- log(int.p4/(1 - int.p4))
    mean.p5 <- log(int.p5/(1 - int.p5))
    mean.p6 <- log(int.p6/(1 - int.p6))
    mean.p7 <- log(int.p7/(1 - int.p7))
    mean.p8 <- log(int.p8/(1 - int.p8))
    mean.p9 <- log(int.p9/(1 - int.p9))
    mean.pA <- log(int.pA/(1 - int.pA))

    int.p1 ~ dunif(0,1)
    int.p2 ~ dunif(0,1)
    int.p3 ~ dunif(0,1)
    int.p4 ~ dunif(0,1)
    int.p5 ~ dunif(0,1)
    int.p6 ~ dunif(0,1)
    int.p7 ~ dunif(0,1)
    int.p8 ~ dunif(0,1)
    int.p9 ~ dunif(0,1)
    int.pA ~ dunif(0,1)

    mu.P <- log(int.phiP/(1 - int.phiP))
    mu.1 <- log(int.phi1/(1 - int.phi1))
    mu.2 <- log(int.phi2/(1 - int.phi2))
    mu.3 <- log(int.phi3/(1 - int.phi3))
    mu.4 <- log(int.phi4/(1 - int.phi4))
    mu.5 <- log(int.phi5/(1 - int.phi5))
    mu.6 <- log(int.phi6/(1 - int.phi6))
    mu.7 <- log(int.phi7/(1 - int.phi7))
    mu.8 <- log(int.phi8/(1 - int.phi8))
    mu.9 <- log(int.phi9/(1 - int.phi9))
    mu.A <- log(int.phiA/(1 - int.phiA))
    
    int.phiP ~ dunif(0,1)
    int.phi1 ~ dunif(0,1)
    int.phi2 ~ dunif(0,1)
    int.phi3 ~ dunif(0,1)
    int.phi4 ~ dunif(0,1)
    int.phi5 ~ dunif(0,1)
    int.phi6 ~ dunif(0,1)
    int.phi7 ~ dunif(0,1)
    int.phi8 ~ dunif(0,1)
    int.phi9 ~ dunif(0,1)
    int.phiA ~ dunif(0,1)
    
    b.sexP[1] <- 0
    b.sex1[1] <- 0
    b.sex2[1] <- 0
    b.sex3[1] <- 0
    b.sex4[1] <- 0
    b.sex5[1] <- 0
    b.sex6[1] <- 0
    b.sexA[1] <- 0
    b.sexP[2] ~ dnorm(0, sd = s.sexP)
    b.sex1[2] ~ dnorm(0, sd = s.sex1)
    b.sex2[2] ~ dnorm(0, sd = s.sex2)
    b.sex3[2] ~ dnorm(0, sd = s.sex3)
    b.sex4[2] ~ dnorm(0, sd = s.sex4)
    b.sex5[2] ~ dnorm(0, sd = s.sex5)
    b.sex6[2] ~ dnorm(0, sd = s.sex6)
    b.sexA[2] ~ dnorm(0, sd = s.sexA)
    s.sexP ~ dexp(1)
    s.sex1 ~ dexp(1)
    s.sex2 ~ dexp(1)
    s.sex3 ~ dexp(1)
    s.sex4 ~ dexp(1)
    s.sex5 ~ dexp(1)
    s.sex6 ~ dexp(1)
    s.sexA ~ dexp(1)
    
    b.massP ~ dnorm(0, sd = s.mass)
    b.mass ~ dnorm(0, sd = s.mass)
    s.mass ~ dexp(1)
    
    b.siteP[2] <- 0
    b.site1[2] <- 0
    b.site2[2] <- 0
    b.siteJ[2] <- 0
    b.siteA[2] <- 0
    b.siteP[1] ~ dnorm(0, sd = s.siteP)
    b.site1[1] ~ dnorm(0, sd = s.site1)
    b.site2[1] ~ dnorm(0, sd = s.site2)
    b.siteJ[1] ~ dnorm(0, sd = s.siteJ)
    b.siteA[1] ~ dnorm(0, sd = s.siteA)
    s.siteP ~ dexp(1)
    s.site1 ~ dexp(1)
    s.site2 ~ dexp(1)
    s.siteJ ~ dexp(1)
    s.siteA ~ dexp(1)
    sigmaP ~ dexp(1)
    sigma1 ~ dexp(1)
    sigma2 ~ dexp(1)
    sigmaJ ~ dexp(1)
    sigmaA ~ dexp(1)
    
    for (t in 1:(n_occasions-1)){
    for (r in 1:2) {
      phiP.prob[r,t] <- 1/(1+exp(-(mu.P + epsP[t] + b.siteP[r])))
      phiPM.prob[r,t] <- 1/(1+exp(-(mu.P + epsP[t] + b.sexP[2] + b.siteP[r])))
      phi1.prob[r,t] <- 1/(1+exp(-(mu.1 + eps1[t] + b.site1[r])))
      phi1M.prob[r,t] <- 1/(1+exp(-(mu.1 + eps1[t] + b.sex1[2] + b.site1[r])))
      phi2.prob[r,t] <- 1/(1+exp(-(mu.2 + eps2[t] + b.site2[r])))
      phi2M.prob[r,t] <- 1/(1+exp(-(mu.2 + eps2[t] + b.sex2[2] + b.site2[r])))
      phi3.prob[r,t] <- 1/(1+exp(-(mu.3 + epsJ[t] + b.siteJ[r])))
      phi3M.prob[r,t] <- 1/(1+exp(-(mu.3 + epsJ[t] + b.sex3[2] + b.siteJ[r])))
      phi4.prob[r,t] <- 1/(1+exp(-(mu.4 + epsJ[t] + b.siteJ[r])))
      phi4M.prob[r,t] <- 1/(1+exp(-(mu.4 + epsJ[t] + b.sex4[2] + b.siteJ[r])))
      phi5.prob[r,t] <- 1/(1+exp(-(mu.5 + epsJ[t] + b.siteJ[r])))
      phi5M.prob[r,t] <- 1/(1+exp(-(mu.5 + epsJ[t] + b.sex5[2] + b.siteJ[r])))
      phi6.prob[r,t] <- 1/(1+exp(-(mu.6 + epsJ[t] + b.siteJ[r])))
      phi6M.prob[r,t] <- 1/(1+exp(-(mu.6 + epsJ[t] + b.sex6[2] + b.siteJ[r])))
      phi7.prob[r,t] <- 1/(1+exp(-(mu.7 + epsA[t] + b.siteA[r])))
      phi7M.prob[r,t] <- 1/(1+exp(-(mu.7 + epsA[t] + b.sexA[2] + b.siteA[r])))
      phi8.prob[r,t] <- 1/(1+exp(-(mu.8 + epsA[t] + b.siteA[r])))
      phi8M.prob[r,t] <- 1/(1+exp(-(mu.8 + epsA[t] + b.sexA[2] + b.siteA[r])))
      phi9.prob[r,t] <- 1/(1+exp(-(mu.9 + epsA[t] + b.siteA[r])))
      phi9M.prob[r,t] <- 1/(1+exp(-(mu.9 + epsA[t] + b.sexA[2] + b.siteA[r])))
      phi10.prob[r,t] <- 1/(1+exp(-(mu.A + epsA[t] + b.siteA[r])))
      phi10M.prob[r,t] <- 1/(1+exp(-(mu.A + epsA[t] + b.sexA[2] + b.siteA[r])))
    }
    } #t
  
    #likelihood
for (i in 1:n_ind) { #females
    z[i, fc[i]:fc[i]] <- 1 #pups at first capture

for (t in (fc[i] + 1):n_occasions) {
      z[i,t] ~ dcat(state_probs[i,t-1,1:12])
      y[i,t] ~ dcat(event_probs[i,t,1:12])
      
    state_probs[i,t-1,1:12] <- getPHI(z = z[i,t-1], 
                                      phiP = phiP[i,t-1], phi1 = phi1[i,t-1], phi2 = phi2[i,t-1], 
                                      phi3 = phi3[i,t-1], phi4 = phi4[i,t-1], phi5 = phi5[i,t-1], 
                                      phi6 = phi6[i,t-1], phi7 = phi7[i,t-1], phi8 = phi8[i,t-1],
                                      phi9 = phi9[i,t-1], phiA = phiA[i,t-1])
    
    event_probs[i,t,1:12] <- getP(z = z[i,t], 
                                    p1 = p1[i,t-1], p2 = p2[i,t-1], p3 = p3[i,t-1], 
                                    p4 = p4[i,t-1], p5 = p5[i,t-1], p6 = p6[i,t-1],
                                    p7 = p7[i,t-1], p8 = p8[i,t-1], p9 = p9[i,t-1],
                                    pA = pA[i,t-1])
    } #t likelihood 
} #i likelihood 
    
}) # mod   

##### run model ####
nim.data <- list(y = y)

nim.constants <- list(n_ind = dim(ch)[1], n_occasions = n_occasions,
                      mass = mass, site = rook, sex = sex,
                      fc = fc)

inits <- list(int.phiP = 0.9, int.phi1 = 0.9, int.phi2 = 0.9, int.phi3 = 0.9, int.phiA = 0.9, 
              int.phi4 = 0.9, int.phi5 = 0.9, int.phi6 = 0.9, int.phi7 = 0.9, int.phi8 = 0.9, int.phi9 = 0.9, 
              mean.p1 = qlogis(0.7), mean.p2 = qlogis(0.6), mean.p3 = qlogis(0.6),
              mean.p4 = qlogis(0.6), mean.p5 = qlogis(0.4), mean.p6 = qlogis(0.6), mean.p7 = qlogis(0.6),
              mean.p8 = qlogis(0.4), mean.p9 = qlogis(0.6), mean.pA = qlogis(0.6),
              b.massP = 0, b.mass = 0, b.sexP = 0, b.sex1 = 0, b.sex2 = 0, b.sex3 = 0, b.sex4 = 0, 
              b.sex5 = 0, b.sex6 = 0, b.sexA = 0, b.siteP = 0, b.site1 = 0, b.site2 = 0, b.siteJ = 0, b.siteA = 0,
              z = z.init)

### parameters
params <- c('int.p1', 'int.p2', 'int.p3', 'int.p4', 'int.p5', 'int.p6', 'int.p7', 'int.p8', 
            'int.p9', 'int.pA', 
            'int.phiP', 'int.phi1', 'int.phi2', 'int.phi3', 'int.phi4', 'int.phi5', 
            'int.phi6', 'int.phi7', 'int.phi8', 'int.phi9', 'int.phiA',
            'phiP.prob', 'phiPM.prob', 'phi1.prob', 'phi1M.prob', 'phi2.prob', 'phi2.prob',
            'phi3.prob', 'phi3M.prob', 'phi4.prob', 'phi4M.prob', 'phi5.prob', 'phi5M.prob',
            'phi6.prob', 'phi6M.prob', 'phi7.prob', 'phi7M.prob', 'phi8.prob', 'phi8M.prob',
            'phi9.prob', 'phi9M.prob', 'phiA.prob', 'phiAM.prob',
            'b.massP', 'b.mass', 'b.sexP', 'b.sex1', 'b.sex2', 'b.sex3', 'b.sex4', 'b.sex5', 'b.sex6',
            'b.sexA', 'b.siteP', 'b.site1', 'b.site2', 'b.siteJ', 'b.siteA',
            'epsP', 'eps1', 'eps2', 'epsJ', 'epsA',
            'z')

### run model
n.iter = 3500; n.chains = 3; n.burnin = 2000; nthin = 3; nAdapt = 20
# n.iter = 35000; n.chains = 3; n.burnin = 20000; nthin = 3; nAdapt = 20


start <- Sys.time()

Rmodel <- nimbleModel(code = SSL_CJS, 
                      constants = nim.constants, data = nim.data, 
                      calculate = F, check = F, inits = inits)

conf <- configureMCMC(Rmodel, monitors = params, control = list(adaptInterval = nAdapt), 
                      thin = nthin, useConjugacy = FALSE, enableWAIC = TRUE)

Rmcmc <- buildMCMC(conf)  #produce uncompiled R mcmc function
Cmodel <- compileNimble(Rmodel)
Cmcmc <- compileNimble(Rmcmc, project = Rmodel)

out <- runMCMC(Cmcmc, niter = n.iter, nburnin = n.burnin, nchains = n.chains, inits = inits,
                 setSeed = FALSE, progressBar = TRUE,
               WAIC = TRUE,
               samplesAsCodaMCMC = TRUE)

saveRDS(out, here::here('results', 'out_ME.RDS')) 

```


```{r results}

out <- readRDS(here::here('results', 'out_null.RDS'))

all_pars <- colnames(out$samples$chain1)
noZ <- all_pars[which(!grepl('z', all_pars))]

outmat <- as.matrix(out$samples)
posts <- outmat[,noZ]

post_sum <- data.frame(
  med = apply(posts, 2, function(x) quantile(x, probs = 0.5, na.rm = T, names = F)),
  lower = apply(posts, 2, function(x) quantile(x, probs = 0.025, na.rm = T, names = F)),
  upper = apply(posts, 2, function(x) quantile(x, probs = 0.975, na.rm = T, names = F)))
post_sum$variable <- row.names(post_sum)


phi.vals <- post_sum %>%
  filter(grepl('phi', variable)) %>%
  transform(age = gsub('int.phi', '', variable)) %>%
  transform(age = factor(age, levels = c('P', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A')))

ggplot(phi.vals, aes(age, med)) +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper))

p.vals <- post_sum %>%
  filter(!grepl('phi', variable)) %>%
  transform(age = gsub('int.p', '', variable)) %>%
  transform(age = factor(age, levels = c('1', '2', '3', '4', '5', '6', '7', '8', '9', 'A')))

ggplot(p.vals, aes(age, med)) +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper))


```


##archive
```{r random effects old}

#b.regP[reg_f[i]] + epsP[reg_f[i],t] 

SSL_CJS <- nimbleCode({

# Priors and constraints
for (i in 1:n_fem) { #females
        for (t in 1:(n_occasions - 1)) {
            logit(phiP[i,t]) <- mu.P + epsP[t] + b.massP*mass[i] 
            logit(delB[i,t]) <- b.delB[resights[i,t]]
            logit(p1[i,t]) <- mean.p1 + b.eff[eff[t]] + eps.p[t] 
        } #t 
  
  for (t in 2:(n_occasions-1)) {
    logit(phi1[i,t]) <- mu.1 + eps1[t] +
              b.mass.1*mass_f[i] 
    logit(p2[i,t]) <- mean.p2 + b.eff[eff[t]] + eps.p[t]
  }
  
  for (t in 3:(n_occasions-1)) {
    logit(phi2[i,t]) <- mu.2 + eps2[t] +
              b.mass.1*mass_f[i] 
    logit(p3[i,t]) <- mean.p3 + b.eff[eff[t]] + eps.p[t]
  }
  
  #first cohort branded in 2000, turn 1 in 2001, turn 3 in 2003, and as 3 yo's could transition
      for (t in 4:(n_occasions-1)) { 
      logit(psi3[i,t]) <- mean.psi3 + eps.psiPB[t] +
             b.mass.psi*mass_f[i]
      logit(phi3[i,t]) <- mu.3 + epsPB[t]
      logit(p4[i,t]) <- mean.p4 + b.eff[eff[t]] + eps.p[t]
      logit(pB[i,t]) <- mean.pB + b.eff[eff[t]] + eps.p[t]
    } #t psi
    
    #first cohort branded in 2000 could have been breeders in 2004 and could breed again the next year
    for (t in 5:(n_occasions-1)) {
      logit(psi4[i,t]) <- mean.psi4 + eps.psiPB[t] +
              b.mass.psi*mass_f[i]
      logit(psiB[i,t]) <- mean.psiB + eps.psiB[t] +
              b.mass.psiB*mass_f[i]
      logit(phi4[i,t]) <- mu.4 + epsPB[t]
      logit(phiB[i,t]) <- mu.B + epsB[t]
      logit(p5[i,t]) <- mean.p5 + b.eff[eff[t]] + eps.p[t]
      logit(pNB[i,t]) <- mean.pNB + b.eff[eff[t]] + eps.p[t]
    } #t psi
    
    #first cohort would be turning 5 in 2005 (t==6) and only 5+ can be transitioning to NB
    for (t in 6:(n_occasions-1)) {  
      logit(psi5[i,t]) <- mean.psi5 + eps.psiPB[t] +
              b.mass.psi*mass_f[i]
      logit(psiNB[i,t]) <- mean.psiNB + eps.psiNB[t] +
              b.mass.psiB*mass_f[i]
      logit(phi5[i,t]) <- mu.5 + epsPB[t]
      logit(phiNB[i,t]) <- mu.NB + epsNB[t]
          } #t psi
} #i fem
  
  for (t in 4:n_occasions) {
      nat_all[t] <- sum(z[1:n_fem,t] > 6 & z[1:n_fem,t] < 10)/sum(z[1:n_fem,t]>4 & z[1:n_fem,t]<12)
      nat4[t] <- sum(z[1:n_fem,t] == 7)/sum(z[1:n_fem,t] == 7 | z[1:n_fem,t] == 5) #4 yo: 7/(5+7)
      nat5[t] <- sum(z[1:n_fem,t] == 8)/sum(z[1:n_fem,t] == 8 | z[1:n_fem,t] == 6 | z[1:n_fem,t] == 10)
      nat6plus[t] <- sum(z[1:n_fem,t] == 9)/sum(z[1:n_fem,t] == 9 | z[1:n_fem,t] == 11) #6+ yo: 9/(9+11)
    }
  
  for (i in 1:n_m) { #males
        for (t in 1:(n_occasions - 1)) {
            logit(phiPM[i,t]) <- mu.PM + epsP[t] +
              b.mass.pm*mass_m[i] 
            logit(p1M[i,t]) <- mean.p1M + b.eff[eff[t]] + eps.p[t] 
        } #t
    
    for (t in 2:(n_occasions-1)) {
            logit(phi1M[i,t]) <- mu.1M + eps1[t] +
              b.mass.1m*mass_m[i] 
            logit(p2M[i,t]) <- mean.p2M + b.eff[eff[t]] + eps.p[t]
          }
    for (t in 3:(n_occasions-1)) {
            logit(phi2M[i,t]) <- mu.2M + eps2[t] +
              b.mass.1m*mass_m[i] 
            logit(p3M[i,t]) <- mean.p3M + b.eff[eff[t]] + eps.p[t]
    }
    for (t in 4:(n_occasions-1)) {
            logit(phi3M[i,t]) <- mu.3M + epsPB[t] 
            logit(p4M[i,t]) <- mean.p4M + b.eff[eff[t]] + eps.p[t]
    }
    for (t in 5:(n_occasions-1)) {
            logit(phi4M[i,t]) <- mu.4M + epsPB[t] 
            logit(p5M[i,t]) <- mean.p5M + b.eff[eff[t]] + eps.p[t]
    }
    for (t in 6:(n_occasions-1)) {
            logit(phi5M[i,t]) <- mu.5M + epsPB[t] 
            logit(pBM[i,t]) <- mean.pBM + b.eff[eff[t]] + eps.p[t]
    }
    for (t in 7:(n_occasions-1)) {
            logit(phiBM[i,t]) <- mu.BM + epsBM[t] 
    }
} #i male
  
### Priors
    mean.psi3 <- log(int.psi3/(1-int.psi3))
    mean.psi4 <- log(int.psi4/(1-int.psi4))
    mean.psi5 <- log(int.psi5/(1-int.psi5))
    mean.psiB <- log(int.psiB/(1-int.psiB))
    mean.psiNB <- log(int.psiNB/(1-int.psiNB))
    int.psi3 ~ dunif(0,1)
    int.psi4 ~ dunif(0,1)
    int.psi5 ~ dunif(0,1)
    int.psiB ~ dunif(0,1)
    int.psiNB ~ dunif(0,1)
    mean.p1 <- log(int.p1/(1 - int.p1))
    mean.p2 <- log(int.p2/(1 - int.p2))
    mean.p3 <- log(int.p3/(1 - int.p3))
    mean.p4 <- log(int.p4/(1 - int.p4))
    mean.p5 <- log(int.p5/(1 - int.p5))
    mean.pB <- log(int.pB/(1 - int.pB))
    mean.pNB <- log(int.pNB/(1 - int.pNB))
    mean.p1M <- log(int.p1M/(1 - int.p1M))
    mean.p2M <- log(int.p2M/(1 - int.p2M))
    mean.p3M <- log(int.p3M/(1 - int.p3M))
    mean.p4M <- log(int.p4M/(1 - int.p4M))
    mean.p5M <- log(int.p5M/(1 - int.p5M))
    mean.pBM <- log(int.pBM/(1 - int.pBM))
    int.p1 ~ dunif(0,1)
    int.p2 ~ dunif(0,1)
    int.p3 ~ dunif(0,1)
    int.p4 ~ dunif(0,1)
    int.p5 ~ dunif(0,1)
    int.pB ~ dunif(0,1)
    int.pNB ~ dunif(0,1)
    int.p1M ~ dunif(0,1)
    int.p2M ~ dunif(0,1)
    int.p3M ~ dunif(0,1)
    int.p4M ~ dunif(0,1)
    int.p5M ~ dunif(0,1)
    int.pBM ~ dunif(0,1)
    mu.P <- log(int.phiP/(1 - int.phiP))
    mu.1 <- log(int.phi1/(1 - int.phi1))
    mu.2 <- log(int.phi2/(1 - int.phi2))
    mu.3 <- log(int.phi3/(1 - int.phi3))
    mu.4 <- log(int.phi4/(1 - int.phi4))
    mu.5 <- log(int.phi5/(1 - int.phi5))
    mu.B <- log(int.phiB/(1 - int.phiB))
    mu.NB <- log(int.phiNB/(1 - int.phiNB))
    mu.PM <- log(int.phiPM/(1 - int.phiPM))
    mu.1M <- log(int.phi1M/(1 - int.phi1M))
    mu.2M <- log(int.phi2M/(1 - int.phi2M))
    mu.3M <- log(int.phi3M/(1 - int.phi3M))
    mu.4M <- log(int.phi4M/(1 - int.phi4M))
    mu.5M <- log(int.phi5M/(1 - int.phi5M))
    mu.BM <- log(int.phiBM/(1 - int.phiBM))
    int.phiP ~ dunif(0,1)
    int.phi1 ~ dunif(0,1)
    int.phi2 ~ dunif(0,1)
    int.phi3 ~ dunif(0,1)
    int.phi4 ~ dunif(0,1)
    int.phi5 ~ dunif(0,1)
    int.phiB ~ dunif(0,1)
    int.phiNB ~ dunif(0,1)
    int.phiPM ~ dunif(0,1)
    int.phi1M ~ dunif(0,1)
    int.phi2M ~ dunif(0,1)
    int.phi3M ~ dunif(0,1)
    int.phi4M ~ dunif(0,1)
    int.phi5M ~ dunif(0,1)
    int.phiBM ~ dunif(0,1)

    p.delB[1] ~ dunif(0,1)
    b.delB[1] <- log(p.delB[1]/(1-p.delB[1]))
    p.delB[2] ~ dunif(0,1)
    b.delB[2] <- log(p.delB[2]/(1-p.delB[2]))
    p.delB[3] ~ dunif(0,1)
    b.delB[3] <- log(p.delB[3]/(1-p.delB[3]))
    b.delB[4] <- -5 #0 on probability scale

    b.eff[1] <- 0
    b.eff[2] ~ dnorm(0, 0.001)
    
    for (t in 1:(n_occasions)) {
      eps.p[t] ~ dnorm(0, sd = sigma.p)
    }

    sigma.p ~ dexp(1)
    
    for (t in 1:(n_occasions-1)){
      epsP[t] ~ dnorm(0, sd = sigmaP)
    } 

    for (t in 2:(n_occasions-1)) {
      eps1[t] ~ dnorm(0, sd = sigma1)
    }
    
    for (t in 3:(n_occasions-1)) {
      eps2[t] ~ dnorm(0, sd = sigma2)
    }
    #first cohort branded in 2000, turn 1 in 2001, turn 3 in 2003, and as 3 yo's could transition
    for (t in 4:(n_occasions-1)) { 
      eps.psiPB[t] ~ dnorm(0, sd = sigma.psiPB)
      epsPB[t] ~ dnorm(0, sd = sigmaPB)
    } #t
    
    #first cohort branded in 2000 could have been breeders in 2004 and could breed again the next year
    for (t in 5:(n_occasions-1)) {
      eps.psiB[t] ~ dnorm(0, sd = sigma.psiB)
      epsB[t] ~ dnorm(0, sd = sigmaB)
      epsBM[t] ~ dnorm(0, sd = sigmaB)
    } #t
    
    #first cohort would be turning 5 in 2005 (t==6) and only 5+ can be transitioning to NB
    for (t in 6:(n_occasions-1)) {
    eps.psiNB[t] ~ dnorm(0, sd = sigma.psiNB)
    epsNB[t] ~ dnorm(0, sd = sigmaNB)
    } #t

  #shrinkage priors
    sigmaP ~ dexp(1)
    sigma1 ~ dexp(1)
    sigma2 ~ dexp(1)
    sigmaPB ~ dexp(1)
    sigmaB ~ dexp(1)
    sigmaNB ~ dexp(1)
    sigma.psiPB ~ dexp(1)
    sigma.psiB ~ dexp(1)
    sigma.psiNB ~ dexp(1)
    
    #covs - psi 
    b.mass.psi ~ dnorm(0, sd = s.mass.psi)
    s.mass.psi ~ dexp(1)
    b.mass.psiB ~ dnorm(0, sd = s.mass.psiB)
    s.mass.psiB ~ dexp(1)

    #covs - phi
    b.mass.p ~ dnorm(0, sd = s.mass.p)
    s.mass.p ~ dexp(1)
    b.mass.pm ~ dnorm(0, sd = s.mass.pm)
    s.mass.pm ~ dexp(1)
    
    b.mass.1 ~ dnorm(0, sd = s.mass.1)
    s.mass.1 ~ dexp(1)
    b.mass.1m ~ dnorm(0, sd = s.mass.1m)
    s.mass.1m ~ dexp(1)
  
    #likelihood
for (i in 1:n_fem) { #females
    z[i, fc[i]:fc[i]] <- 1 #pups at first capture

for (t in (fc[i] + 1):n_occasions) {
      z[i,t] ~ dcat(state_probs[i,t-1,1:12])
      y[i,t] ~ dcat(event_probs[i,t,1:11])
      
    state_probs[i,t-1,1:12] <- getPHI_f(z = z[i,t-1], 
                                      phiP = phiP[i,t-1], phi1 = phi1[i,t-1], phi2 = phi2[i,t-1], 
                                      phi3 = phi3[i,t-1], phi4 = phi4[i,t-1], phi5 = phi5[i,t-1], 
                                      phiB = phiB[i,t-1], phiNB = phiNB[i,t-1],
                                      psi3 = psi3[i,t-1], psi4 = psi4[i,t-1],
                                      psi5 = psi5[i,t-1], psiB = psiB[i,t-1], psiNB = psiNB[i,t-1])
    
    event_probs[i,t,1:11] <- getP_f(z = z[i,t], 
                                    p1 = p1[i,t-1], p2 = p2[i,t-1], p3 = p3[i,t-1], 
                                    p4 = p4[i,t-1], p5 = p5[i,t-1],
                                    pB = pB[i,t-1], pNB = pNB[i,t-1], delB = delB[i,t-1])
    } #t likelihood fem
} #i likelihood fem
    
   for (i in 1:n_m) { #males
    zm[i, fc_m[i]:fc_m[i]] <- 1
  for (t in (fc_m[i] + 1):n_occasions) {
    zm[i,t] ~ dcat(state_probs_m[i, t-1, 1:8])
    ym[i,t] ~ dcat(event_probs_m[i,t,1:8])
    
    state_probs_m[i,t-1,1:8] <- getPHI_m(z = zm[i,t-1], 
                                      phiPM = phiPM[i,t-1], phi1M = phi1M[i,t-1], phi2M = phi2M[i,t-1], 
                                      phi3M = phi3M[i,t-1], phi4M = phi4M[i,t-1], phi5M = phi5M[i,t-1], 
                                      phiBM = phiBM[i,t-1])
    event_probs_m[i,t,1:8] <- getP_m(z = zm[i,t], 
                                    p1M = p1M[i,t-1], p2M = p2M[i,t-1], p3M = p3M[i,t-1], 
                                    p4M = p4M[i,t-1], p5M = p5M[i,t-1], pBM = pBM[i,t-1])
    } # likelihood t male
   } #likelihood i male
    
}) # mod   

##### run model ####

nim.data <- list(y = y, ym = ym, 
                 z = z.st, zm = z.st.m)

nim.constants <- list(n_fem = dim(ch_fem)[1], n_m = dim(ch_m)[1], 
                      n_occasions = n_occasions, resights = res_mat, eff = eff,
                      mass_f = mass_f, mass_m = mass_m,
                      fc = fc, fc_m = fc_m)

inits <- list(int.phiP = 0.9, int.phiPM = 0.9, int.phi1 = 0.9, int.phi1M = 0.9,
              int.phi2 = 0.9, int.phi2M = 0.9, int.phi3 = 0.9, int.phi3M = 0.9,
              int.phi4 = 0.9, int.phi4M = 0.9, int.phi5 = 0.9, int.phi5M = 0.75,
              int.phiB = 0.9, int.phiBM = 0.8, int.phiNB = 0.9, 
              mean.psi3 = qlogis(0.25), mean.psi4 = qlogis(0.6), mean.psi5 = qlogis(0.25),
              mean.psiB = qlogis(0.9), mean.psiNBM = 0.2, 
              mean.p1 = qlogis(0.7), mean.p2 = qlogis(0.6),
              mean.p3 = qlogis(0.6),mean.p4 = qlogis(0.6),
              mean.p5 = qlogis(0.4), mean.pB = 0.8, mean.pNB = qlogis(0.4),
              mean.p1M = qlogis(0.5), mean.p2M = qlogis(0.5), mean.p3M = qlogis(0.5), 
              mean.p4M = qlogis(0.5), 
              mean.pBM = qlogis(0.8), mean.p5M = qlogis(0.6),
              eps.p = c(rep(0, n_occasions)), 
              epsP = rep(0, n_occasions-1), eps1 = rep(0, n_occasions-1), eps2 = rep(0, n_occasions-1),
              epsPB = rep(0, n_occasions-1), epsB = rep(0, n_occasions-1), 
              epsNB = rep(0, n_occasions-1), epsBM = rep(0, n_occasions-1),
              eps.psiPB = rep(0, n_occasions-1), 
              eps.psiB = rep(0, n_occasions-1), eps.psiNB = rep(0, n_occasions-1),
              sigmaPB = 1, sigmaP = 1, sigmaB = 1, sigma2 = 1, sigma1 = 1, sigma.psi = 1,
              p.delB = c(0.4, 0.5, 0.75), 
              b.mass.p = 0, b.mass.pm = 0, b.mass.psi = 0, b.mass.psiB = 0,
              b.mass.1 = 0, b.mass.1m = 0, 
              z = z.init, zm = z.init.m)

### parameters
params <- c('mean.p1', 'mean.p2', 'mean.p3', 'mean.p4', 'mean.p5', 'mean.pB', 'mean.pNB',
            'mean.p1M', 'mean.p2M', 'mean.p3M', 'mean.p4M', 'mean.p5M', 'mean.pBM', 
            "mean.psi3", 'mean.psi4', 'mean.psi5', 'mean.psiB', 'mean.psiNB',
            'int.p1', 'int.p2', 'int.p3', 'int.p4', 'int.p5', 'int.pB', 'int.pNB', 
            'int.p1M', 'int.p2M', 'int.p3M', 'int.p4M', 'int.p5M', 'int.pBM',  
            'int.psi3', 'int.psi4', 'int.psi5', 'int.psiB', 'int.psiNB',
            'int.phiP', 'int.phi1', 'int.phi2', 'int.phi3', 'int.phi4', 'int.phi5', 'int.phiB', 'int.phiNB',
            'int.phiPM', 'int.phi1M', 'int.phi2M', 'int.phi3M', 'int.phi4M', 'int.phi5M', 'int.phiBM',
            'epsP', 'eps1', 'eps2','epsPB','epsB', 'epsNB', 'epsBM',
            'eps.psiPB', 'eps.psiB', 'eps.psiNB',
            'b.delB', 'p.delB','b.eff', 'eps.p', 
             'sigmaP', 'sigma1', 'sigma2', 'sigmaPB', 'sigmaB', 'sigmaNB',
            'sigma.psiPB', 'sigma.psiB', 'sigma.psiNB','sigma.p', 
            'b.mass.p', 'b.mass.1', 'b.mass.pm', 'b.mass.1m', 'b.mass.psi', 'b.mass.psiB',
            'z', 'zm', 'mu.P', 'mu.1', 'mu.2', 'mu.3', 'mu.4', 'mu.5', 'mu.B', 'mu.NB', 
            'mu.PM', 'mu.1M', 'mu.2M', 'mu.3M', 'mu.4M', 'mu.5M', 'mu.BM')

### run model
n.iter = 35000; n.chains = 3; n.burnin = 20000; nthin = 3; nAdapt = 20

start <- Sys.time()

Rmodel <- nimbleModel(code = SSL_CJS, 
                      constants = nim.constants, data = nim.data, 
                      calculate = F, check = F, inits = inits)

conf <- configureMCMC(Rmodel, monitors = params, control = list(adaptInterval = nAdapt), 
                      thin = nthin, useConjugacy = FALSE)


Rmcmc <- buildMCMC(conf, enableWAIC = TRUE)  #produce uncompiled R mcmc function
Cmodel <- compileNimble(Rmodel)
Cmcmc <- compileNimble(Rmcmc, project = Rmodel)

out <- runMCMC(Cmcmc, niter = n.iter, nburnin = n.burnin, nchains = n.chains, inits = inits,
                 setSeed = FALSE, progressBar = TRUE,
               WAIC = TRUE,
               samplesAsCodaMCMC = TRUE)

```

